# Generated by Django 3.2.8 on 2021-10-21 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211019_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 12, 24, 0, 0)),
        ),
    ]
